feature-management:
  Beta: true
  FeatureV:
    EnabledFor:
      -
        Name: percentageFilter
        Parameters:
          PercentageFilterSetting: "50"
      -
        Name: timeWindowFilter
        Parameters:
          TimeWindowFilterSettingStart: "Fri, 6 Dec 2019 00:59:30 GMT"
          TimeWindowFilterSettingEnd: "Sat, 2 May 2020 22:59:30 GMT"