spring:
  thymeleaf:
    cache: false
  cloud:
    azure:
      appconfiguration:
        watch:
          enabled: True
          delay: 5s
config:
  message: Hi
FeatureManagement:
  Beta: true
  DarkTheme:
    EnabledFor:
      -
        Name: Random
        Parameters:
          chance: "50"
  BetaAB:
    EnabledFor:
      -
        Name: Random
        Parameters:
          chance: "50"
      -
        Name: ClientFilter
        Parameters:
          clientIp: 10.0.0.1 