spring:
  thymeleaf:
    cache: false
config:
   message: "Hi"
FeatureManagement:
  Beta: true
  FeatureV:
    EnabledFor:
      -
        Name: percentageFilter
        Parameters:
          PercentageFilterSetting: "50"